blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using hun7rex
    url: https://github.com/0x71rex/hun7rex/discussions/categories/q-a
    about: Ask a question or request support for using hun7rex

  - name: Share idea / feature to discuss for hun7rex
    url: https://github.com/0x71rex/hun7rex/discussions/categories/ideas
    about: Share idea / feature to discuss for hun7rex

  - name: Connect with 0x71rex (Discord)
    url: https://discord.gg/cTKMyNuDNH
    about: Connect with 0x71rex for direct communication